apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: mirrormaker2-cluster-offsets
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 25
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824