site_name: Event Driven Architecture 
repo_url: https://github.com/ibm-cloud-architecture/refarch-eda
nav:
  - Home: index.md
  - Concepts: concepts/README.md
  - Architecture: 
    - Reference diagrams: architecture.md
    - Event sources: evt-src/README.md
    - Event backbone: evt-backbone/README.md
    - Event actions: evt-action/README.md
    - Event managed states: evt-state/README.md
    - Event Stream & Kafka architecture: kafka/arch.md
  - Methodology: 
    - Event driven methodology: methodology/readme.md
    - Event Storming: methodology/eventstorming.md
    - Event Storming applied to container shipment analysis: https://ibm-cloud-architecture.github.io/refarch-kc/analysis/readme/
    - Domain driven design: methodology/ddd.md
  - Event driven patterns:
    - Microservices: evt-microservices/README.md
    - Event-driven patterns: evt-microservices/ED-patterns.md
    - Kafka streaming processing: kafka/kafka-stream.md
    - Data replication pattern: https://ibm-cloud-architecture.github.io/refarch-data-ai-analytics/preparation/data-replication/
  - Reference implementations:
    - Container shipment implementation solution: https://ibm-cloud-architecture.github.io/refarch-kc
  - Product guidances:
    - Kafka architecture: kafka/arch.md
    - Kafka concepts summary: kafka/readme.md
    - Kafka producer development practices:  kafka/producers.md
    - Kafka consumer development practices: kafka/consumers.md
    - Kafka FAQ: kafka/FAQ.md
    - Kafka monitoring: kafka/monitoring.md
    - Serverless: serverless/README.md
  - Deployments:
      - Event Streams IBM CLOUD deployment: deployments/eventstreams/es-ibm-cloud.md
      - Event Streams ICP deployment: deployments/eventstreams/README.md
      - Kafka deployment: deployments/kafka/README.md
      - Zookeeper deployment: deployments/zookeeper/README.md
      - Postgresql: deployments/postgresql/README.md
      - Ceph deployment on ICP: deployments/eventstreams/Install_Ceph_on_ICP.md
      - Kafka deployment with Strimzi: deployments/strimzi/deploy.md
      - ICP troubleshouting: https://github.com/ibm-cloud-architecture/refarch-integration/blob/master/docs/icp/troubleshooting.md
  - Real time analytics: 
    - Concepts: rt-analytics/README.md
    - Reefer Container Predictive Maintenance: https://github.com/jbcodeforce/refarch-reefer-ml
  - Skill journey: training/eda-skill-journey.md
  - Compendium: compendium.md
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences