site_name: Event Driven Architecture 
nav:
  - Home: index.md
  - Concepts: concepts/README.md
  - Architecture: 
    - Reference diagrams: architecture.md
    - Event Sources: evt-src/README.md
    - Event Backbone: evt-backbone/README.md
    - Event Actions: evt-action/README.md
    - Event Managed States: evt-state/README.md
  - Event Storming: 
    - Workshop: methodology/readme.md
    - Applied to Container Shipment Analysis: https://ibm-cloud-architecture.github.io/refarch-kc/analysis/readme/
  - Event driven patterns:
    - Microservices: evt-microservices/README.md
    - Event patterns: evt-microservices/ED-patterns.md
  - Real time analytics: rt-analytics/README.md
  - Product guidances:
    - Kafka summary: kafka/readme.md
    - Kafka producer:  kafka/producers.md
    - Kafka consumer: kafka/consumers.md
    - Kafka deployment: deployments/kafka/README.md
    - Zookeeper deployment: deployments/zookeeper/README.md
    - Event Streams deployment: deployments/eventstreams/README.md
    - Serverless: serverless/README.md
  - Skill Journey: eda-skill-journey.md
  - Compendium: compendium.md
theme: material
extra_css: ["extra.css"]
