site_name: Event Driven Architecture 
repo_url: https://github.com/ibm-cloud-architecture/refarch-eda
nav:
  - Home: index.md
  - Concepts: concepts/README.md
  - Architecture: 
    - Reference diagrams: architecture.md
    - Event Sources: evt-src/README.md
    - Event Backbone: evt-backbone/README.md
    - Event Actions: evt-action/README.md
    - Event Managed States: evt-state/README.md
    - Event Stream - Kafka architecture: kafka/arch.md
    - Data Replication Pattern: kafka/data-replication.md
  - Event Storming: 
    - Event Storming Workshop: methodology/readme.md
    - Applied to Container Shipment Analysis: https://ibm-cloud-architecture.github.io/refarch-kc/analysis/readme/
    - Domain driven design: methodology/ddd.md
  - Event driven patterns:
    - Microservices: evt-microservices/README.md
    - Event-driven patterns: evt-microservices/ED-patterns.md
    - Event streaming processing: kafka/kafka-stream.md
    - Data Replication Pattern: kafka/data-replication.md
  - Real time analytics: rt-analytics/README.md
  - Reference implementations:
    - Container shipment implementation solution: https://ibm-cloud-architecture.github.io/refarch-kc
  - Product guidances:
    - Kafka architecture: kafka/arch.md
    - Kafka concepts summary: kafka/readme.md
    - Kafka producer:  kafka/producers.md
    - Kafka consumer: kafka/consumers.md
    - Kafka deployment: deployments/kafka/README.md
    - Zookeeper deployment: deployments/zookeeper/README.md
    - Event Streams ICP deployment: deployments/eventstreams/README.md
    - Kafka Monitoring: kafka/monitoring.md
    - Serverless: serverless/README.md
    - Postgresql: deployments/postgresql/README.md
  - Skill Journey: eda-skill-journey.md
  - Compendium: compendium.md
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences